### ISSUE TITLE
Enable SSL on www.wifiqrcode.net

### ISSUE THREAD

**Issue by lightswitch05** [oseemann/wifi-qr-code-generator#1]
I understand that the client does not send any data, but it would still be nice to see SSL enabled on this page. Github has free custom domain hosting support with SSL certs provided by LetsEncrypt. 

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by oseemann** [comment]
Good point. Certificate is now live. Thanks

**Comment by lightswitch05** [comment]
Wow, that was fast. Thanks!
